export const data = [
  {
    id: 1,
    category: 'บริการฝั่งเข็ม',
    filter: true,
    cover: '/mock/type-1.jpg',
    avatar: '/mock/mock-1.png',
    cert: '/mock/certificate.png',
    detail: 'บริการฝังเข็มที่เหมาะสำหรับทุกคน',
    title: 'คลินิกเวชกรรมฝังเข็มสบายตัว',
    doctor_name: 'สมศักดิ์ งามวงศ์วาน',
    rating: 4,
    location: 'บางรัก',
    distance: 7.3,
    price: 'high',
    filter: 1,
    categoryNo: 1,
  },
  {
    id: 2,
    category: 'การแพทย์แผนโบราณ',
    filter: false,
    cover: '/mock/type-2.jpg',
    avatar: '/mock/mock-2.png',
    cert: '/mock/certificate.png',
    detail: 'บริการแพทย์แผนโบราณที่มีอายุกว่า 70 ปี',
    title: 'คลินิกการแพทย์แผนไทยรติมาฃ',
    doctor_name: 'รติมา แจ้งวัฒนะ',
    rating: 4,
    location: 'หลักสี่',
    distance: 10.4,
    price: 'med',
    filter: 2,
    categoryNo: 2,
  },
  {
    id: 3,
    category: 'การจัดกระดูก',
    filter: false,
    cover: '/mock/type-3.jpg',
    avatar: '/mock/mock-3.png',
    cert: '/mock/certificate.png',
    detail: 'จัดกระดูกแก้ office symdrome',
    title: 'เช็กคลินิกการแพทย์แผนไทยประยุกต์',
    doctor_name: 'เช็ก ลาดปลาเค้า',
    rating: 4,
    location: 'หลักสี่',
    distance: 5.8,
    price: 'high',
    filter: 3,
    categoryNo: 3,
  },
  {
    id: 4,
    category: 'อื่น ๆ',
    filter: false,
    cover: '/mock/type-4.jpeg',
    avatar: '/mock/mock-4.png',
    cert: '/mock/certificate.png',
    detail: 'บริการด้วยคุณภาพ ลงมือทำด้วยหัวใจ',
    title: 'คลินิกเทคนิการแพทย์รักคุณ',
    doctor_name: 'ฝน ประชาอุทิศ',
    rating: 4,
    location: 'ดอนเมือง',
    distance: 3.0,
    price: 'low',
    filter: 4,
    categoryNo: 4,
  },
  {
    id: 5,
    category: 'บริการฝั่งเข็ม',
    filter: true,
    cover: '/mock/type-1.jpg',
    avatar: '/mock/mock-5.png',
    cert: '/mock/certificate.png',
    detail: 'คลินิกฝังเข็มเพื่อการดูแบหน้า',
    title: 'คลินิกเวชกรรมงามหน้า',
    doctor_name: 'ชาติ ปู่เจ้าสมิงพราบ',
    rating: 4,
    location: 'ปากเกร็ด',
    distance: 6.5,
    price: 'low',
    filter: 1,
    categoryNo: 5,
  },
  {
    id: 6,
    category: 'อื่น ๆ',
    filter: true,
    cover: '/mock/type-4.jpeg',
    avatar: '/mock/mock-6.png',
    cert: '/mock/certificate.png',
    detail: 'ประสบการณ์แพทย์แผนไทยของคุณจะเปลี่ยนไป',
    title: 'เจียมคลินิกการแพทย์แผนไทย',
    doctor_name: 'เจียม สุขสวัสดิ์',
    rating: 4,
    location: 'หนองจอก',
    distance: 40.0,
    price: 'high',
    filter: 2,
    categoryNo: 2,
  },
  {
    id: 7,
    category: 'การแพทย์แผนโบราณ',
    filter: true,
    cover: '/mock/type-2.jpg',
    avatar: '/mock/mock-7.png',
    cert: '/mock/certificate.png',
    detail: 'การแพทย์แผนโบราณที่ทำมากว่า 100 ปี',
    title: 'คลินิกการแพทย์แผนไทยประยุกต์ดอกไม้',
    doctor_name: 'หญิง นวมินทร์',
    rating: 4,
    location: 'ลาดพร้าว',
    distance: 25.7,
    price: 'med',
    filter: 3,
    categoryNo: 3,
  },
  {
    id: 8,
    category: 'การจัดกระดูก',
    filter: false,
    cover: '/mock/type-3.jpg',
    avatar: '/mock/mock-8.png',
    cert: '/mock/certificate.png',
    detail: 'การจัดกระดูกสำหรับคนเป็น office symdrome',
    title: 'เทพรักษ์คลินิกจัดกระดูก',
    doctor_name: 'นพดล เทพรักษ์',
    rating: 4,
    location: 'บางขุนเทียน',
    distance: 17.3,
    price: 'high',
    filter: 4,
    categoryNo: 5,
  },
  {
    id: 9,
    category: 'บริการฝั่งเข็ม',
    filter: false,
    cover: '/mock/type-1.jpg',
    avatar: '/mock/mock-9.png',
    cert: '/mock/certificate.png',
    detail: 'เวชกรรมเฉพาะทางสำหรับผู้สูงอายุ',
    title: 'คลินิกเวชกรรมเฉพาะทางยุทธุ์',
    doctor_name: 'ยุทธุ์ วิภาวดี',
    rating: 4,
    location: 'บางใหญ่',
    distance: 12.6,
    price: 'med',
    filter: 1,
    categoryNo: 1,
  },
  {
    id: 10,
    category: 'อื่น ๆ',
    filter: false,
    cover: '/mock/type-4.jpeg',
    avatar: '/mock/mock-10.png',
    cert: '/mock/certificate.png',
    detail: 'คลินกเวชกรรมสำหรับผู้หญิง',
    title: 'เล็กคลินิกเวชกรรมเฉพาะทาง',
    doctor_name: 'เล็ก มหาไชย',
    rating: 4,
    location: 'บางบอน',
    distance: 39.0,
    price: 'med',
    filter: 2,
    categoryNo: 5,
  },
];
